[tool.poetry]
name = "backtest"
version = "0.2.0"
description = ""
authors = ["Wei Liu"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"